BibliotecaMVC/src/BibliotecaMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace BibliotecaMVC.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

BibliotecaMVC/src/BibliotecaMVC/ViewComponents/ListagemLivrosViewComponent.cs
using BibliotecaMVC.Data;
using BibliotecaMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BibliotecaMVC.ViewComponents
{
    public class ListagemLivrosViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _context;
        public ListagemLivrosViewComponent(ApplicationDbContext c)
        {
            _context = c;
        }
        public async Task<IViewComponentResult> InvokeAsync(int autorID)
        {
            var produtos = await GetListagemLivrosAsync(autorID);
            return View(produtos);
        }
        private Task<IEnumerable<Livro>> GetListagemLivrosAsync(int autorID)
        {
            var livros = _context.Livro.AsNoTracking()
            .Include(l => l.LivroAutores)
            .ThenInclude(li => li.Autor)
            .OrderBy(l => l.Titulo);

            if (autorID != 0)
                livros.Where(x => x.LivroAutores.Any(y => y.AutorID == autorID));
            return Task.FromResult(livros.AsEnumerable());
        }
    }
}

BibliotecaMVC/src/BibliotecaMVC/Views/Home/About.cshtml
@{
    ViewData["Title"] = "Sobre";
    ViewData["Message"] = "Projeto Biblioteca MVC";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Aluno: Thiago Silva Cerqueira</p>
<p>FIB Bauru - MBA Engenharia de Software</p>

BibliotecaMVC/src/BibliotecaMVC/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contatos";    
}
<h2>@ViewData["Title"]</h2>

<address>
    Thiago Silva Cerqueira<br />
    Rua Padre João 17030 <br />
    <abbr title="Fone">Fone / Whatsapp:</abbr>
    (14) 99892-0793
</address>

<address>
    <strong>E-mail:</strong> <a href="mailto:thiagoscerqueira@gmail.com">thiagoscerqueira@gmail.com</a><br />    
</address>

BibliotecaMVC/src/BibliotecaMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<p class="lead">Verifique os livros da nossa Biblioteca !!</p>
<div>
    @await Component.InvokeAsync("ListagemLivros", "")
</div>